const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),test=require("node:test"),vm=require("node:vm");
const root=path.resolve(__dirname,"..");const context=vm.createContext({console,setTimeout(){},clearTimeout(){},document:{getElementById(){return{parentElement:{classList:{add(){},remove(){}}}};}}});context.window=context;
for(const file of ["js/data.js","js/character.js","js/enemy-defense.js","js/boss-phase.js","js/mujin.js","js/baekrin.js","js/skills.js","js/defense.js","js/combat.js"])vm.runInContext(fs.readFileSync(path.join(root,file),"utf8"),context,{filename:file});
const W=context.Wuxia,noop=()=>{};
function game(){const calls={damage:[],poise:[]};const g={mode:"duel",enemyConfig:W.ENEMIES.baekrin,camera:{update:noop,reset:noop,release:noop,focusBetween:noop,punch:noop,shake:noop,pan:noop,follow:noop},effects:{clear:noop,update:noop,trackSword:noop,slash:noop,shockwave:noop,dust:noop,afterimage:noop,add:noop,reactionLabel:noop,spark:noop,poise:(x,y,v)=>calls.poise.push(v),damage:(...a)=>calls.damage.push(a)},audio:{unlock:noop,tone:noop,slash:noop,hit:noop,breakPoise:noop,dash:noop,charge:noop,clash:noop},shell:{classList:{add:noop,remove:noop,toggle:noop}},updateUI:noop,setMessage:noop,showSkillTitle:noop,callout:noop,cinematic:noop,flash:noop};g.player=new W.Character(W.PLAYER_DATA,335,476);g.enemy=new W.Character(W.BAEKRIN_DATA,945,476);g.combat=new W.Combat(g);g.combat.ai=false;g.combat.reset();return g;}
const skill=id=>W.BAEKRIN_SKILLS.find(s=>s.id===id);
test("Baekrin has exact stats, spear, arena, and fixed cycle",()=>{const d=W.BAEKRIN_DATA;assert.deepEqual([d.maxHp,d.attack,d.defense,d.crit,d.speed,d.maxPoise,d.poiseRecovery],[14600,100,70,.1,104,115,9]);assert.equal(d.weaponStyle,"spear");assert.deepEqual(Object.keys(W.ENEMIES.baekrin),Object.keys(W.ENEMIES.baekrin));const g=game();assert.equal(g.combat.intent.id,"spearThrust");assert.equal(g.combat.baekrin.label,"설원창 1/3");g.combat.baekrin.advanceAfter(skill("spearThrust"));assert.equal(g.combat.intent.id,"spearChain");g.combat.baekrin.advanceAfter(skill("spearChain"));assert.equal(g.combat.intent.id,"spearSweep");g.combat.baekrin.advanceAfter(skill("spearSweep"));assert.equal(g.combat.intent.id,"spearThrust");});
test("Baekrin recovery inserts once and resumes interrupted step",()=>{const g=game(),ai=g.combat.baekrin;ai.step=1;g.enemy.poise=31;ai.prepareNext();assert.equal(g.combat.intent.id,"snowRecover");const held=ai.step;ai.advanceAfter(skill("snowRecover"));assert.equal(ai.step,held);assert.equal(g.combat.intent.id,"spearChain");const r=new W.EnemySkillRunner(g.combat,g.enemy,g.player,skill("snowRecover"));for(let t=0;t<.9;t+=.02)r.update(.02);assert.equal(g.enemy.poise,55);});
test("Baekrin openings and response thresholds match existing rules",()=>{assert.equal(W.evaluateOpening(W.BAEKRIN_OPENINGS.spearThrust,"SLASH").result,"exploit");assert.equal(W.evaluateOpening(W.BAEKRIN_OPENINGS.spearThrust,"THRUST").result,"resisted");assert.equal(W.evaluateOpening(W.BAEKRIN_OPENINGS.spearChain,"MULTI").result,"exploit");assert.equal(W.evaluateOpening(W.BAEKRIN_OPENINGS.spearSweep,"THRUST").result,"exploit");for(const [id,guard,poise,cost] of [["spearChain","counter",52,18],["spearSweep","counter",42,14]]){const g=game();g.player.guard=guard;g.player.poise=poise;const r=new W.EnemySkillRunner(g.combat,g.enemy,g.player,skill(id));assert.equal(r.outcome,"parry");r.parry();assert.equal(g.player.poise,poise-cost);}});
test("Baekrin response timelines restore positions and poses",()=>{for(const id of ["spearThrust","spearChain","spearSweep","snowRecover"]){const g=game();g.player.guard=id==="spearThrust"?"evade":null;const r=new W.EnemySkillRunner(g.combat,g.enemy,g.player,skill(id));g.combat.runner=r;let done=false;g.combat.skillFinished=()=>{done=true;};for(let t=0;t<2.2&&!done;t+=.02){r.update(.02);if(r.awaitingResponse)r.acceptResponse(null);}assert.equal(done,true,id);assert.equal(g.enemy.x,g.enemy.baseX,id);assert.equal(g.enemy.poseOverride,null,id);assert.equal(g.enemy.getSwordTip().x!==g.enemy.getHandPosition().x,true,id);}});
